/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MediShieldPreCheckInterface extends Interface {
  getFunction(
    nameOrSignature: "checkEligibility" | "getLastEligibility" | "protocolId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EligibilityEvaluated"): EventFragment;

  encodeFunctionData(
    functionFragment: "checkEligibility",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastEligibility",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace EligibilityEvaluatedEvent {
  export type InputTuple = [
    applicant: AddressLike,
    categoryHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    applicant: string,
    categoryHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    applicant: string;
    categoryHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MediShieldPreCheck extends BaseContract {
  connect(runner?: ContractRunner | null): MediShieldPreCheck;
  waitForDeployment(): Promise<this>;

  interface: MediShieldPreCheckInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkEligibility: TypedContractMethod<
    [
      ageHandle: BytesLike,
      ageProof: BytesLike,
      historyHandle: BytesLike,
      historyProof: BytesLike,
      chronicHandle: BytesLike,
      chronicProof: BytesLike,
      lifestyleHandle: BytesLike,
      lifestyleProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getLastEligibility: TypedContractMethod<
    [account: AddressLike],
    [[string, bigint] & { categoryHandle: string; evaluatedAt: bigint }],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkEligibility"
  ): TypedContractMethod<
    [
      ageHandle: BytesLike,
      ageProof: BytesLike,
      historyHandle: BytesLike,
      historyProof: BytesLike,
      chronicHandle: BytesLike,
      chronicProof: BytesLike,
      lifestyleHandle: BytesLike,
      lifestyleProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLastEligibility"
  ): TypedContractMethod<
    [account: AddressLike],
    [[string, bigint] & { categoryHandle: string; evaluatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EligibilityEvaluated"
  ): TypedContractEvent<
    EligibilityEvaluatedEvent.InputTuple,
    EligibilityEvaluatedEvent.OutputTuple,
    EligibilityEvaluatedEvent.OutputObject
  >;

  filters: {
    "EligibilityEvaluated(address,bytes32,uint256)": TypedContractEvent<
      EligibilityEvaluatedEvent.InputTuple,
      EligibilityEvaluatedEvent.OutputTuple,
      EligibilityEvaluatedEvent.OutputObject
    >;
    EligibilityEvaluated: TypedContractEvent<
      EligibilityEvaluatedEvent.InputTuple,
      EligibilityEvaluatedEvent.OutputTuple,
      EligibilityEvaluatedEvent.OutputObject
    >;
  };
}
