/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    MediShieldPreCheck: {
      address: "0x6b2ce889faa4EeA304D04A9C6EBE06326d61B6C5",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "applicant",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "categoryHandle",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "EligibilityEvaluated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "externalEuint8",
              name: "ageHandle",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "ageProof",
              type: "bytes",
            },
            {
              internalType: "externalEbool",
              name: "historyHandle",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "historyProof",
              type: "bytes",
            },
            {
              internalType: "externalEbool",
              name: "chronicHandle",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "chronicProof",
              type: "bytes",
            },
            {
              internalType: "externalEbool",
              name: "lifestyleHandle",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "lifestyleProof",
              type: "bytes",
            },
          ],
          name: "checkEligibility",
          outputs: [
            {
              internalType: "bytes32",
              name: "categoryHandle",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "getLastEligibility",
          outputs: [
            {
              internalType: "bytes32",
              name: "categoryHandle",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "evaluatedAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9623687,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
